### ISSUE TITLE
Callback after completing each batch of tasks?

### ISSUE THREAD

**Issue by panda-moe-zz** [feross/run-parallel-limit#12]
This is just a feature request. We can have callbacks after each batch of parallel requests is completed. Will try to send in a PR if I get around to it :)

**Comment by feross** [comment]
Thanks for reporting this issue. Due to time constraints, I don't have any plans to work on this so I'm going to close it.

![mickey-wizard](https://user-images.githubusercontent.com/121766/62907205-e7fc7680-bd26-11e9-83f3-9614f069b5e0.gif)
